AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Multi-Agentic Trading Supervisor - AWS Lambda deployment for Bedrock Agent integration

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.13
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO
        ACTION_GROUP_NAME: TradingTools
        API_PATH: /analyze

Parameters:
  AlphaVantageApiKey:
    Type: String
    Description: Alpha Vantage API key for sentiment analysis (optional)
    Default: ''
    NoEcho: true
  
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:
  TradingSupervisorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'trading-supervisor-${Environment}'
      Description: Multi-Agentic Trading Supervisor for stock analysis
      CodeUri: .
      Handler: src.lambda_handler.lambda_handler
      Role: !GetAtt TradingSupervisorExecutionRole.Arn
      Environment:
        Variables:
          ALPHA_VANTAGE_API_KEY: !Ref AlphaVantageApiKey
      Tags:
        Project: TradingSupervisor
        Environment: !Ref Environment
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
            RestApiId: !Ref TradingApi

  TradingSupervisorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'trading-supervisor-execution-role-${Environment}'
      Description: Execution role for Trading Supervisor Lambda function
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        # Basic Lambda execution permissions
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TradingSupervisorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudWatch Logs permissions
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/trading-supervisor-${Environment}:*'
              # Optional: Add Bedrock permissions if needed
              # - Effect: Allow
              #   Action:
              #     - bedrock:InvokeAgent
              #   Resource: '*'

  TradingSupervisorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/trading-supervisor-${Environment}'
      RetentionInDays: 7

  TradingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'trading-api-${Environment}'
      StageName: !Ref Environment
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'POST,GET,OPTIONS'"

  # Bedrock Agent Resource (optional - can be created separately)
  # TradingBedrockAgent:
  #   Type: AWS::Bedrock::Agent
  #   Properties:
  #     AgentName: !Sub 'trading-supervisor-${Environment}'
  #     Description: Multi-agentic trading analysis system
  #     Instruction: You are a fund manager that analyzes stocks using technical and sentiment analysis tools.
  #     FoundationModel: anthropic.claude-v2
  #     ActionGroups:
  #       - ActionGroupName: TradingTools
  #         Description: Tools for stock analysis
  #         ActionGroupExecutor:
  #           Lambda: !GetAtt TradingSupervisorFunction.Arn

Outputs:
  TradingSupervisorFunctionArn:
    Description: ARN of the Trading Supervisor Lambda function
    Value: !GetAtt TradingSupervisorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'
  
  TradingSupervisorFunctionName:
    Description: Name of the Trading Supervisor Lambda function
    Value: !Ref TradingSupervisorFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'
  
  TradingSupervisorRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt TradingSupervisorExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref TradingSupervisorLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'
  
  TradingApiUrl:
    Description: API Gateway endpoint URL for Trading Supervisor
    Value: !Sub 'https://${TradingApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/analyze'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'
